### ISSUE TITLE
Check For Update for Add-on

### ISSUE THREAD

**Issue by abdullah1038** [joyfullservice/msaccess-vcs-integration#294] opened 2021-12-30 03:55 UTC
Hi,

The plugin is very nice and useful. Thank you very much for your effort. This post is not an issue exactly but a request/suggestion. How about putting an option to check for addon update automatically as well as on-demand? Is it possible?

Best Regards

**Comment by hecon5** [comment] 2021-12-30 12:50
Thanks! This is related to #118, probably is the same thing. There's a few hurdles to overcome, but it's definitely a desired outcome. To be clear, I submitted the above issue, but after pondering it, I am not sure the work to get it right is worth it.

The biggest problem with checking for updates is that this is an Access addin, not a regular program. "Phoning home" becomes very difficult in some security environments, because it looks like Access is reaching out to the web, and some Network admins frown heavily on this (mine included).

The second thing is how to talk to github and check versions, which requires processing and handling web queries and payloads.

The last issue, and is arguably the hardest, is updating the addon in Access, which requires you to close Access, copy files, relaunch in some cases, close, then reopen the original file. 

Then, you have to decide...did you even want to update? Because many of the recent changes we've made change the export / import code, which mades merging changes from others (or reverting back to prior builds) very difficult. 

Compare this with simply having a link to the webpage, where you can see if there is a new version, see any changes, download at your leisure, install when you have coordinated with your team, determined if the export changes are worth it, and install by clicking when you don't have your work open. 

Not to say it can't be done, but it's got a lot of pieces moving to get it done correctly. 

If you have some ideas and can tackle these for a PR, by all means, take a stab :)

**Comment by abdullah1038** [comment] 2021-12-31 03:21
Thanks for reply @hecon5, I had seen the source code of this add-on but it is way advanced then my current level of VBA knowledge. I have used check for updates option in my project with none of the code written by me. I used sample db provided in access world forum by isladogs. What it does in my case is as follows:

> it download a text file (or a webpage as text file) from a webserver using URLDownloadToFile method. The text file contain version number and changelog.

> Compares the version with the current version of the file and if it is larger than the file version, it informs the user along with the changelog and provide user with a link to download the latest version. It's up to user whether update or not.

**Comment by hecon5** [comment] 2022-02-23 18:00
@abdullah1038: I missed your reply before...my apologies. 
Since there's already a feature request for this, are you good closing this as a duplicate? 

Duplicate of #118

**Closed** 2022-02-23 18:53 UTC
Labels: duplicate

**Comment by abdullah1038** [comment] 2022-02-24 01:21
Thanks for reply. Yes please, close it.
