### ISSUE TITLE
Git integration

### ISSUE THREAD

**Issue by GeekMustHave** [joyfullservice/msaccess-vcs-integration#211] opened 2021-04-02 19:17 UTC
I'm a little confused how the GIT integration works. Just got started using this add-in.

I have a .git repository in the directory where the exported files are.

I can manually for the git commands to merge and comment the commit.

Is there more to the GIT integration that what I Understand right now?

**Comment by hecon5** [comment] 2021-04-12 14:18
This looks like a duplicate of joyfullservice#210?

**Closed** 2021-04-12 14:29 UTC
Labels: duplicate
