### ISSUE TITLE
TrustedLocation does not save correctly.

### ISSUE THREAD

**Issue by hecon5** [joyfullservice/msaccess-vcs-integration#124] opened 2021-01-14 18:24 UTC
(New issue as old one closed).
Additional troubleshooting: 
I have discovered that after installing/coping to Addins and adding as a trusted location, Access would not accept it as a trusted file until I'd gone to the `addins` folder and then opened the file, and "enabled" it. Once this was done, it appears to work nicely.

_Originally posted by @hecon5 in https://github.com/joyfullservice/msaccess-vcs-integration/issues/120#issuecomment-760174624_

**Comment by hecon5** [comment] 2021-01-14 18:29
I'll test out if making a cmd script would launch the addin so the user could do this right away after install (and so they don't need to know where it is); this would cut down on steps needed to run the installer.

**Comment by joyfullservice** [comment] 2021-01-14 19:35
Thanks for the update! By the way, feel free to add comments to closed issues if something is still unresolved. I can re-open the issue to continue working on it. (It helps keep all the discussion in one place.) I will go ahead and close this issue as a duplicate, and we can continue the dialog there. Duplicate of #120

**Comment by joyfullservice** [comment] 2021-01-14 19:36
Duplicate of #120

**Closed** 2021-01-14 19:44 UTC
