### ISSUE TITLE
Says its "installed" in the add in manager but its disabled in the options menu 

### ISSUE THREAD

**Issue by StingyJack** [joyfullservice/msaccess-vcs-integration#28] opened 2020-05-21 13:43 UTC
is this due to a policy or setting on my end?

**Comment by joyfullservice** [comment] 2020-05-21 17:58
Great question! What version of Access are you using? You might check the Trust Center settings to see if something might be locked down there....

![2020-05-21 12_54_08-Version Control System](https://user-images.githubusercontent.com/7254992/82589887-6e6da080-9b62-11ea-8a5d-847ec3911860.jpg)

Let me know which settings you find to be the problem, and I will consider putting a note on the installation page to help other users.

**Comment by joyfullservice** [comment] 2020-05-22 12:05
I will go ahead and close out this issue, but feel free to reopen it if you determine that this is caused by something specific to this add-in.

**Comment by cenx1** [comment] 2020-05-22 12:28
I am getting the same behavior with Addin installed but disabled under the Options->Addi-Ins section. What is working for me is to rename the registry keys (I am putting **VCS** in front of all key names) and remove the version keyname. Then it works perfectly.

**Comment by joyfullservice** [comment] 2020-05-23 14:04
Thanks for the additional details! Would one of you be able to test a couple things for me? The _version key_ is needed to be able to use the add-in with an ADP project, but it seems to work with several variations of _value_ for this key. What happens if you change the Version registry key to 1 or 2? Or if you replace it with a string value instead? I haven't come across any clear documentation on exactly what this value represents, but it does seem to be required for the add-in to work on an ADP project in Access 2010. 

Let me know if you find a combination that works in your version of Office, and I will test it in 32-bit 2010 to see if we can identify a solution that works for both. Thanks again for the help and feedback!

**Comment by StingyJack** [comment] 2020-05-24 03:03
Sorry, had to wait until weekend,,, this version of Access 
![image](https://user-images.githubusercontent.com/15381181/82744628-22c91b80-9d49-11ea-8f19-a40cc0ff6885.png)

Trust center looks like yours on the Add-Ins page
![image](https://user-images.githubusercontent.com/15381181/82744636-42604400-9d49-11ea-90ff-91162f935ed0.png)


This is what the Add-Ins tab looks like for me currently
![image](https://user-images.githubusercontent.com/15381181/82744641-56a44100-9d49-11ea-9fc7-5a00249c535a.png)

The Add-Ins manager 
![image](https://user-images.githubusercontent.com/15381181/82744651-73407900-9d49-11ea-95d9-6dbcb0ec250b.png)

If I run it as admin, I can click the Install button and a checkbox appears to the left of "Version Control", but I dont get any more choices from the Add-Ins ribbon menu button. Perhaps it just had a problem on install... are there directions for how to totally remove it and all traces from my pc so I can try again?

**Comment by StingyJack** [comment] 2020-05-24 03:07
If I double click the accdb file from where I put it, I get
![image](https://user-images.githubusercontent.com/15381181/82744693-fd88dd00-9d49-11ea-9d9a-79795a2504d4.png)

Then click OK and get
![image](https://user-images.githubusercontent.com/15381181/82744701-1db89c00-9d4a-11ea-9694-8193e2fc628f.png)


I'm thinking maybe the d/l got hosed?

**Comment by StingyJack** [comment] 2020-05-24 04:14
That I think is the same place that #23 refers to. Added PtrSafe after the declare, File --> "SaveVersion Control", closed Access. Opened Access as administrator, picked the "Version Control.accda" I had saved and it says it installed successfully and will be available on next launch. 

The Add-In manager now thinks its installed. 
![image](https://user-images.githubusercontent.com/15381181/82745478-da166000-9d52-11ea-97cd-6d852e81979d.png)

But I dont see any buttons or actions for this add-in to execute it. There's a Source Control tab/menu thats in the Ribbon customizations but that I dont see actually displayed. 
![image](https://user-images.githubusercontent.com/15381181/82745534-8c4e2780-9d53-11ea-8bd1-32328bb34eee.png)

**Comment by cenx1** [comment] 2020-05-25 09:23
I have installed v3.1.5 with no modifictions and now the add-in is installing fine and available in the ribbon menu. :-)

**Comment by joyfullservice** [comment] 2020-05-25 16:50
See #23 and #24 for related discussions. I believe this has been resolved in the latest release, but feel free to reopen the issue if you encounter further problems with the installer on 64-bit Access.

**Closed by joyfullservice** 2020-05-25 16:50 UTC

**Comment by joyfullservice** [comment] 2020-05-25 22:06
@StingyJack - Would you be able to try the latest installer to see if it works correctly on your system? You can find it on the [Releases ](https://github.com/joyfullservice/msaccess-vcs-integration/releases)tab.

**Comment by StingyJack** [comment] 2020-06-01 11:22
Just double click the file? 

Should I remove older installs? (How?)

**Comment by joyfullservice** [comment] 2020-06-01 13:51
Yes, you can just double-click the file to start the installation. If the program finds an older installation that required admin access, you will prompted with the opportunity to remove it. Going forward it doesn't require admin rights to install or upgrade.
